[build]
  command = "yarn install --production=false && node build.js"
  environment = { GENERATE_SOURCEMAP = "false", NETLIFY_USE_YARN = "true", NODE_ENV = "production" }

[[plugins]]
  package = "netlify-plugin-subfont"

[[plugins]]
  package = "netlify-plugin-minify-html"

[[plugins]]
  package = "netlify-plugin-inline-source"

[[plugins]]
  package = "netlify-plugin-inline-critical-css"
