[build]
  command = "next build && next export"
  publish = "out"

[[plugins]]
  package = "netlify-plugin-image-optim"

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]
    baseUrl = "https://kaelbot.xyz"
    sitemapPath = "/sitemap.xml"
    providers = [
      "google"
    ]
